using Microsoft.AspNetCore.Builder; using Microsoft.Extensions.Configuration; using Microsoft.Extensions.DependencyInjection; using Microsoft.Extensions.Hosting; using Microsoft.Extensions.Logging;
using System.Threading.Channels; using MailKit.Net.Smtp; using Mediator; using Microsoft.Extensions.Options; using MimeKit; using Nimble.Modulith.Email.Contracts;
namespace Nimble.Modulith.Email;
public record EmailMessage(string To,string Subject,string Body,string? From=null);
public class EmailSettings { public string SmtpServer{get;set;}="localhost"; public int SmtpPort{get;set;}=25; public bool EnableSsl{get;set;}=false; public string Username{get;set;}=""; public string Password{get;set;}=""; public string DefaultFromAddress{get;set;}="noreply@nimblemodulith.com"; }
public interface IQueueService<T>{ ValueTask EnqueueAsync(T item,CancellationToken ct=default); ValueTask<T> DequeueAsync(CancellationToken ct=default); }
public class ChannelQueueService<T>:IQueueService<T>{ private readonly Channel<T> _ch=Channel.CreateUnbounded<T>(); public ValueTask EnqueueAsync(T item,CancellationToken ct=default)=>_ch.Writer.WriteAsync(item,ct); public ValueTask<T> DequeueAsync(CancellationToken ct=default)=>_ch.Reader.ReadAsync(ct); }
public interface IEmailSender { Task SendEmailAsync(EmailMessage message,CancellationToken ct=default); }
public class SmtpEmailSender(ILogger<SmtpEmailSender> logger,IOptions<EmailSettings> options):IEmailSender
{ public async Task SendEmailAsync(EmailMessage m,CancellationToken ct=default){ var s=options.Value; var msg=new MimeMessage(); msg.From.Add(MailboxAddress.Parse(m.From??s.DefaultFromAddress)); msg.To.Add(MailboxAddress.Parse(m.To)); msg.Subject=m.Subject; msg.Body=new TextPart("plain"){Text=m.Body}; using var client=new SmtpClient(); await client.ConnectAsync(s.SmtpServer,s.SmtpPort,s.EnableSsl,ct); if(!string.IsNullOrWhiteSpace(s.Username)) await client.AuthenticateAsync(s.Username,s.Password,ct); await client.SendAsync(msg,ct); await client.DisconnectAsync(true,ct); logger.LogInformation("Email sent to {To}",m.To);} }
public class SendEmailCommandHandler(IQueueService<EmailMessage> q):ICommandHandler<SendEmailCommand>{ public async ValueTask<Unit> Handle(SendEmailCommand c,CancellationToken ct){ await q.EnqueueAsync(new(c.To,c.Subject,c.Body,c.From),ct); return Unit.Value; } }
public class EmailSendingBackgroundWorker(IQueueService<EmailMessage> q,IEmailSender sender,ILogger<EmailSendingBackgroundWorker> logger):BackgroundService
{ protected override async Task ExecuteAsync(CancellationToken stoppingToken){ logger.LogInformation("Email worker started"); while(!stoppingToken.IsCancellationRequested){ try{ var m=await q.DequeueAsync(stoppingToken); await sender.SendEmailAsync(m,stoppingToken);} catch(OperationCanceledException){} catch(Exception ex){ logger.LogError(ex,"Email send failed"); await Task.Delay(3000,stoppingToken);} } } }
public static class EmailModuleExtensions
{ public static WebApplicationBuilder AddEmailModuleServices(this WebApplicationBuilder builder, Serilog.ILogger logger){ builder.Services.Configure<EmailSettings>(builder.Configuration.GetSection("Email")); builder.Services.AddSingleton(typeof(IQueueService<>),typeof(ChannelQueueService<>)); builder.Services.AddSingleton<IEmailSender,SmtpEmailSender>(); builder.Services.AddHostedService<EmailSendingBackgroundWorker>(); logger.Information("Email module services registered"); return builder; } }
