using Microsoft.AspNetCore.Builder; using Microsoft.Extensions.DependencyInjection; using Microsoft.Extensions.Hosting;
using Ardalis.Result; using FastEndpoints; using Mediator; using Microsoft.EntityFrameworkCore; using Nimble.Modulith.Customers.Contracts; using Nimble.Modulith.Email.Contracts; using Nimble.Modulith.Products.Contracts; using Nimble.Modulith.Users.Contracts;
namespace Nimble.Modulith.Customers;
public class Address{public string Street{get;set;}="";public string City{get;set;}="";public string State{get;set;}="";public string PostalCode{get;set;}="";public string Country{get;set;}="";}
public class Customer{public int Id{get;set;}public string FirstName{get;set;}="";public string LastName{get;set;}="";public string Email{get;set;}="";public string PhoneNumber{get;set;}="";public Address Address{get;set;}=new();public DateTime CreatedAt{get;set;}=DateTime.UtcNow;public string FullName=>$"{FirstName} {LastName}";}
public enum OrderStatus{Pending=0,Confirmed=1,Processing=2,Shipped=3,Delivered=4,Cancelled=5}
public class OrderItem{public int Id{get;set;}public int OrderId{get;set;}public int ProductId{get;set;}public string ProductName{get;set;}="";public int Quantity{get;set;}public decimal UnitPrice{get;set;}public decimal TotalPrice=>Quantity*UnitPrice;}
public class Order{public int Id{get;set;}public int CustomerId{get;set;}public Customer? Customer{get;set;}public string OrderNumber{get;set;}="";public DateOnly OrderDate{get;set;}public OrderStatus Status{get;set;}=OrderStatus.Pending;public DateTime CreatedAt{get;set;}=DateTime.UtcNow;public List<OrderItem> Items{get;set;}=[];public decimal TotalAmount=>Items.Sum(i=>i.TotalPrice); public void AddItem(OrderItem item){ if(Status!=OrderStatus.Pending) throw new InvalidOperationException("Only pending orders can be changed"); var existing=Items.FirstOrDefault(x=>x.ProductId==item.ProductId); if(existing is null) Items.Add(item); else existing.Quantity+=item.Quantity;} }
public class CustomersDbContext(DbContextOptions<CustomersDbContext> options):DbContext(options){public DbSet<Customer> Customers=>Set<Customer>();public DbSet<Order> Orders=>Set<Order>();public DbSet<OrderItem> OrderItems=>Set<OrderItem>();protected override void OnModelCreating(ModelBuilder b){b.HasDefaultSchema("Customers");b.Entity<Customer>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Email).IsRequired().HasMaxLength(256);e.HasIndex(x=>x.Email).IsUnique();e.OwnsOne(x=>x.Address);}); b.Entity<Order>(e=>{e.HasKey(x=>x.Id);e.HasMany(x=>x.Items).WithOne().HasForeignKey(x=>x.OrderId).OnDelete(DeleteBehavior.Cascade);e.Ignore(x=>x.TotalAmount);e.Property(x=>x.Status).HasConversion<string>();}); b.Entity<OrderItem>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.UnitPrice).HasColumnType("decimal(18,2)");e.Ignore(x=>x.TotalPrice);});}}
public static class CustomersModuleExtensions{public static IHostApplicationBuilder AddCustomersModuleServices(this IHostApplicationBuilder b,Serilog.ILogger l){b.AddSqlServerDbContext<CustomersDbContext>("customersdb");l.Information("Customers module services registered");return b;} public static async Task<WebApplication> EnsureCustomersModuleDatabaseAsync(this WebApplication app){using var s=app.Services.CreateScope();var db=s.ServiceProvider.GetRequiredService<CustomersDbContext>();await db.Database.EnsureCreatedAsync();return app;}}
public record CustomerRequest(string FirstName,string LastName,string Email,string PhoneNumber,string Street,string City,string State,string PostalCode,string Country); public record CustomerResponse(int Id,string FirstName,string LastName,string Email,string PhoneNumber,string Street,string City,string State,string PostalCode,string Country);
static class Map{public static CustomerResponse ToResp(Customer c)=>new(c.Id,c.FirstName,c.LastName,c.Email,c.PhoneNumber,c.Address.Street,c.Address.City,c.Address.State,c.Address.PostalCode,c.Address.Country);} 
public class ListCustomers(CustomersDbContext db):EndpointWithoutRequest<List<CustomerResponse>>{ public override void Configure(){Get("/customers");Roles("Admin");Tags("customers");} public override async Task HandleAsync(CancellationToken ct){ var customers=await db.Customers.AsNoTracking().ToListAsync(ct); await Send.OkAsync(customers.Select(Map.ToResp).ToList(),ct); }}
public class GetCustomer(CustomersDbContext db):EndpointWithoutRequest<CustomerResponse>{ public override void Configure(){Get("/customers/{id}");Tags("customers");} public override async Task HandleAsync(CancellationToken ct){var id=Route<int>("id"); var c=await db.Customers.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id,ct); if(c is null){await Send.NotFoundAsync(ct);return;} if(!User.IsInRole("Admin") && !string.Equals(User.Identity?.Name,c.Email,StringComparison.OrdinalIgnoreCase)){await Send.ForbiddenAsync(ct);return;} await Send.OkAsync(Map.ToResp(c),ct);} }
public class CreateCustomer(CustomersDbContext db, IMediator mediator):Endpoint<CustomerRequest,CustomerResponse>{ public override void Configure(){Post("/customers");Tags("customers");} public override async Task HandleAsync(CustomerRequest r,CancellationToken ct){ if(!User.IsInRole("Admin") && User.Identity?.Name!=r.Email){await Send.ForbiddenAsync(ct);return;} var c=new Customer{FirstName=r.FirstName,LastName=r.LastName,Email=r.Email,PhoneNumber=r.PhoneNumber,Address=new(){Street=r.Street,City=r.City,State=r.State,PostalCode=r.PostalCode,Country=r.Country}}; db.Customers.Add(c); await db.SaveChangesAsync(ct); var pwd=Guid.NewGuid().ToString("N")[..12]; await mediator.Send(new CreateUserCommand(c.Email,pwd),ct); await mediator.Send(new SendEmailCommand(c.Email,"Welcome to Nimble Modulith",$"Your temporary password is: {pwd}"),ct); await Send.OkAsync(Map.ToResp(c),ct);} }
public record CreateOrderItemRequest(int ProductId,int Quantity); public record CreateOrderRequest(int CustomerId,DateOnly OrderDate,List<CreateOrderItemRequest> Items); public record OrderItemResponse(int Id,int ProductId,string ProductName,int Quantity,decimal UnitPrice,decimal TotalPrice); public record OrderResponse(int Id,int CustomerId,string OrderNumber,DateOnly OrderDate,OrderStatus Status,decimal TotalAmount,List<OrderItemResponse> Items);
static class OrderMap{public static OrderResponse ToResp(Order o)=>new(o.Id,o.CustomerId,o.OrderNumber,o.OrderDate,o.Status,o.TotalAmount,o.Items.Select(i=>new OrderItemResponse(i.Id,i.ProductId,i.ProductName,i.Quantity,i.UnitPrice,i.TotalPrice)).ToList());}
public class CreateOrder(CustomersDbContext db,IMediator mediator):Endpoint<CreateOrderRequest,OrderResponse>{ public override void Configure(){Post("/orders");Tags("orders");} public override async Task HandleAsync(CreateOrderRequest r,CancellationToken ct){ var customer=await db.Customers.FindAsync([r.CustomerId],ct); if(customer is null){await Send.NotFoundAsync(ct);return;} if(!User.IsInRole("Admin") && User.Identity?.Name!=customer.Email){await Send.ForbiddenAsync(ct);return;} var order=new Order{CustomerId=r.CustomerId,OrderNumber=$"ORD-{DateTime.UtcNow:yyyyMMddHHmmss}",OrderDate=r.OrderDate}; foreach(var item in r.Items){var p=await mediator.Send(new GetProductDetailsQuery(item.ProductId),ct); order.AddItem(new OrderItem{ProductId=p.Id,ProductName=p.Name,UnitPrice=p.Price,Quantity=item.Quantity});} db.Orders.Add(order); await db.SaveChangesAsync(ct); await Send.OkAsync(OrderMap.ToResp(order),ct);} }
public class GetOrder(CustomersDbContext db):EndpointWithoutRequest<OrderResponse>{ public override void Configure(){Get("/orders/{id}");Tags("orders");} public override async Task HandleAsync(CancellationToken ct){var id=Route<int>("id"); var o=await db.Orders.Include(x=>x.Items).Include(x=>x.Customer).FirstOrDefaultAsync(x=>x.Id==id,ct); if(o is null){await Send.NotFoundAsync(ct);return;} if(!User.IsInRole("Admin") && User.Identity?.Name!=o.Customer?.Email){await Send.ForbiddenAsync(ct);return;} await Send.OkAsync(OrderMap.ToResp(o),ct);} }
public record AddOrderItemRequest(int ProductId,int Quantity);
public class AddOrderItem(CustomersDbContext db,IMediator mediator):Endpoint<AddOrderItemRequest,OrderResponse>{ public override void Configure(){Post("/orders/{id}/items");Tags("orders");} public override async Task HandleAsync(AddOrderItemRequest r,CancellationToken ct){var id=Route<int>("id"); var o=await db.Orders.Include(x=>x.Items).Include(x=>x.Customer).FirstOrDefaultAsync(x=>x.Id==id,ct); if(o is null){await Send.NotFoundAsync(ct);return;} if(!User.IsInRole("Admin") && User.Identity?.Name!=o.Customer?.Email){await Send.ForbiddenAsync(ct);return;} var p=await mediator.Send(new GetProductDetailsQuery(r.ProductId),ct); o.AddItem(new OrderItem{ProductId=p.Id,ProductName=p.Name,UnitPrice=p.Price,Quantity=r.Quantity}); await db.SaveChangesAsync(ct); await Send.OkAsync(OrderMap.ToResp(o),ct);} }
public class DeleteOrderItem(CustomersDbContext db):EndpointWithoutRequest{ public override void Configure(){Delete("/orders/{id}/items/{itemId}");Tags("orders");} public override async Task HandleAsync(CancellationToken ct){var id=Route<int>("id");var itemId=Route<int>("itemId");var o=await db.Orders.Include(x=>x.Items).FirstOrDefaultAsync(x=>x.Id==id,ct); if(o is null||o.Status!=OrderStatus.Pending){await Send.ErrorsAsync(400,ct);return;} var item=o.Items.FirstOrDefault(x=>x.Id==itemId); if(item is null){await Send.NotFoundAsync(ct);return;} db.Remove(item); await db.SaveChangesAsync(ct); await Send.NoContentAsync(ct);} }
public class ListOrdersByDate(CustomersDbContext db):EndpointWithoutRequest<List<OrderResponse>>{ public override void Configure(){Get("/orders/by-date/{date}");Roles("Admin");Tags("orders");} public override async Task HandleAsync(CancellationToken ct){var d=Route<DateOnly>("date"); var orders=await db.Orders.Include(x=>x.Items).Where(x=>x.OrderDate==d).ToListAsync(ct); await Send.OkAsync(orders.Select(OrderMap.ToResp).ToList(),ct);} }
public class ConfirmOrder(CustomersDbContext db,IMediator mediator):EndpointWithoutRequest<OrderResponse>{ public override void Configure(){Post("/orders/{id}/confirm");Tags("orders");} public override async Task HandleAsync(CancellationToken ct){var id=Route<int>("id"); var o=await db.Orders.Include(x=>x.Items).Include(x=>x.Customer).FirstOrDefaultAsync(x=>x.Id==id,ct); if(o is null){await Send.NotFoundAsync(ct);return;} if(!User.IsInRole("Admin") && User.Identity?.Name!=o.Customer!.Email){await Send.ForbiddenAsync(ct);return;} o.Status=OrderStatus.Confirmed; await db.SaveChangesAsync(ct); await mediator.Publish(new OrderCreatedEvent(o.Id,o.OrderNumber,o.OrderDate,o.CustomerId,o.Customer!.Email,o.Customer.FullName,o.TotalAmount,o.Items.Select(i=>new OrderCreatedItem(i.Id,i.ProductId,i.ProductName,i.Quantity,i.UnitPrice,i.TotalPrice)).ToList()),ct); await mediator.Send(new SendEmailCommand(o.Customer.Email,$"Order Confirmation - {o.OrderNumber}",$"Thank you for your order. Total: {o.TotalAmount:C}"),ct); await Send.OkAsync(OrderMap.ToResp(o),ct);} }
