using Microsoft.AspNetCore.Builder; using Microsoft.Extensions.DependencyInjection; using Microsoft.Extensions.Hosting;
using FastEndpoints; using Mediator; using Microsoft.EntityFrameworkCore; using Nimble.Modulith.Products.Contracts;
namespace Nimble.Modulith.Products;
public class Product{ public int Id{get;set;} public string Name{get;set;}=""; public string Description{get;set;}=""; public decimal Price{get;set;} public DateTime DateCreated{get;set;}=DateTime.UtcNow; public string CreatedByUser{get;set;}="system"; }
public class ProductsDbContext(DbContextOptions<ProductsDbContext> options):DbContext(options){ public DbSet<Product> Products=>Set<Product>(); protected override void OnModelCreating(ModelBuilder b){ b.HasDefaultSchema("Products"); b.Entity<Product>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Name).IsRequired().HasMaxLength(200);e.Property(x=>x.Description).HasMaxLength(1000);e.Property(x=>x.Price).HasColumnType("decimal(18,2)");e.HasData(new Product{Id=1,Name="Sample Product",Description="Demo product",Price=19.99m,CreatedByUser="seed"},new Product{Id=2,Name="Another Product",Description="Second demo",Price=29.99m,CreatedByUser="seed"});}); } }
public static class ProductsModuleExtensions{ public static IHostApplicationBuilder AddProductsModuleServices(this IHostApplicationBuilder b,Serilog.ILogger l){b.AddSqlServerDbContext<ProductsDbContext>("productsdb");l.Information("Products module services registered");return b;} public static async Task<WebApplication> EnsureProductsModuleDatabaseAsync(this WebApplication app){using var s=app.Services.CreateScope();var db=s.ServiceProvider.GetRequiredService<ProductsDbContext>();await db.Database.EnsureCreatedAsync();return app;} }
public record ProductRequest(string Name,string Description,decimal Price); public record ProductResponse(int Id,string Name,string Description,decimal Price,DateTime DateCreated,string CreatedByUser);
public class ListProducts(ProductsDbContext db):EndpointWithoutRequest<List<ProductResponse>>{ public override void Configure(){Get("/products");AllowAnonymous();Tags("products");} public override async Task HandleAsync(CancellationToken ct)=> await Send.OkAsync(await db.Products.AsNoTracking().Select(p=>new ProductResponse(p.Id,p.Name,p.Description,p.Price,p.DateCreated,p.CreatedByUser)).ToListAsync(ct),ct);}
public class GetProduct(ProductsDbContext db):EndpointWithoutRequest<ProductResponse>{ public override void Configure(){Get("/products/{id}");AllowAnonymous();Tags("products");} public override async Task HandleAsync(CancellationToken ct){var id=Route<int>("id"); var p=await db.Products.FindAsync([id],ct); if(p is null){await Send.NotFoundAsync(ct);return;} await Send.OkAsync(new(p.Id,p.Name,p.Description,p.Price,p.DateCreated,p.CreatedByUser),ct);} }
public class CreateProduct(ProductsDbContext db):Endpoint<ProductRequest,ProductResponse>{ public override void Configure(){Post("/products");Roles("Admin");Tags("products");} public override async Task HandleAsync(ProductRequest r,CancellationToken ct){var p=new Product{Name=r.Name,Description=r.Description,Price=r.Price,CreatedByUser=User.Identity?.Name??"admin"}; db.Products.Add(p); await db.SaveChangesAsync(ct); await Send.CreatedAtAsync<GetProduct>(new{id=p.Id},new(p.Id,p.Name,p.Description,p.Price,p.DateCreated,p.CreatedByUser),cancellation:ct);} }
public class UpdateProduct(ProductsDbContext db):Endpoint<ProductRequest,ProductResponse>{ public override void Configure(){Put("/products/{id}");Roles("Admin");Tags("products");} public override async Task HandleAsync(ProductRequest r,CancellationToken ct){var id=Route<int>("id");var p=await db.Products.FindAsync([id],ct); if(p is null){await Send.NotFoundAsync(ct);return;} p.Name=r.Name;p.Description=r.Description;p.Price=r.Price; await db.SaveChangesAsync(ct); await Send.OkAsync(new(p.Id,p.Name,p.Description,p.Price,p.DateCreated,p.CreatedByUser),ct);} }
public class DeleteProduct(ProductsDbContext db):EndpointWithoutRequest{ public override void Configure(){Delete("/products/{id}");Roles("Admin");Tags("products");} public override async Task HandleAsync(CancellationToken ct){var id=Route<int>("id");var p=await db.Products.FindAsync([id],ct); if(p is null){await Send.NotFoundAsync(ct);return;} db.Remove(p); await db.SaveChangesAsync(ct); await Send.NoContentAsync(ct);} }
public class GetProductPriceQueryHandler(ProductsDbContext db):IQueryHandler<GetProductPriceQuery,decimal>{ public async ValueTask<decimal> Handle(GetProductPriceQuery q,CancellationToken ct)=> (await db.Products.AsNoTracking().FirstAsync(p=>p.Id==q.ProductId,ct)).Price; }
public class GetProductDetailsQueryHandler(ProductsDbContext db):IQueryHandler<GetProductDetailsQuery,ProductDetailsResult>{ public async ValueTask<ProductDetailsResult> Handle(GetProductDetailsQuery q,CancellationToken ct){var p=await db.Products.AsNoTracking().FirstOrDefaultAsync(p=>p.Id==q.ProductId,ct)??throw new InvalidOperationException($"Product {q.ProductId} not found"); return new(p.Id,p.Name,p.Price);} }
